Cargo.lock
Cargo.toml
src/main.rs
src/syncer.rs

Add `--path-filter` option

---

src/asyncutil/lsg.rs
src/syncer.rs

Fixes to program termination

---

Cargo.toml
README.md

Set MSRV to 1.80

---

.github/workflows/test.yml

This repository uses Dependabot, not Renovate.

test.yml: Fix cache non-activation check

---

Cargo.lock
Cargo.toml
src/s3/mod.rs

In order to avoid a broken version of `rustls`

Remove `reqwest` dependency

---

README.md
src/main.rs

Fill in README and `--help` text

---

README.md
src/main.rs

Add `--log-level` option

---

src/main.rs
src/s3/mod.rs
src/syncer.rs

Add more logging

---

CHANGELOG.md
src/inventory/list.rs
src/s3/mod.rs

Delete inventory list files after processing

---

Cargo.toml

Add `release-debug` profile to `Cargo.toml`

---

src/syncer.rs

Fix locking on current file paths

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/inventory/item.rs
src/keypath.rs
src/main.rs
src/syncer.rs
src/util.rs

Validate item keys when deserializing CSVs

---

.github/workflows/build.yml

Add workflow for uploading built executables

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/syncer.rs
src/util.rs

Delete paths with file type conflicts

---

src/inventory/item.rs
src/inventory/list.rs
src/syncer.rs

Ignore empty directory entries in CSVs

---

CHANGELOG.md
src/s3/mod.rs

See https://github.com/dandi/s3invsync/issues/81#issuecomment-2557179635

Increase S3 retry count to 10

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
src/s3/mod.rs

Support optional AWS credentials

---

CHANGELOG.md
Cargo.toml
src/syncer.rs

Treat Ctrl-C like an internal error

---

src/syncer.rs

Closes #40.
There should be no need for any further cleanup logic here.

Remove to-dos that won't be done

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
src/inventory/fields.rs
src/inventory/item.rs
src/inventory/list.rs
src/inventory/mod.rs
src/manifest.rs
src/s3/mod.rs
src/syncer.rs

Support all documented S3 Inventory fields in inventory lists

---

CHANGELOG.md
README.md
src/main.rs
src/s3/mod.rs
src/s3/streams.rs

Add `--list-dates` option

---

Cargo.toml

Add keywords & categories

---

CHANGELOG.md
README.md
src/errorset.rs
src/inventory/list.rs
src/main.rs
src/s3/mod.rs
src/syncer/mod.rs

Add `--ok-errors` option

---

README.md

Document relation between `--trace-progress` and `-l TRACE`

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
src/consts.rs
src/keypath.rs
src/syncer/metadata.rs
src/syncer/mod.rs
src/syncer/statefile.rs
src/util.rs

Store start & successful end times of program runs in `.s3invsync.state.json`

---

CHANGELOG.md
README.md
src/inventory/fields.rs
src/inventory/item.rs
src/syncer/metadata.rs
src/util.rs

Support objects without version IDs

---

CHANGELOG.md
README.md
src/errorset.rs
src/s3/mod.rs
src/syncer/mod.rs

Closes #158.
@kabilar Try this PR.

Add `access-denied` item to `--ok-errors`

---

CHANGELOG.md
README.md
src/errorset.rs
src/s3/mod.rs
src/syncer/mod.rs

Closes #166.
@aaronkanzer Try this.

Support converting `InvalidObjectState` errors to warnings
